# 项目级 Gradle 配置
org.gradle.jvmargs=-Xmx2048m -XX:MaxMetaspaceSize=512m
org.gradle.parallel=true

android.useAndroidX=true
android.enableJetifier=true

# 新架构开关（与 MainApplication.kt 中 BuildConfig 对应）
newArchEnabled=true
hermesEnabled=true

# RN 模板生成的变量占位（实际值由 react-native-gradle-plugin 注入）
reactNativeArchitectures=armeabi-v7a,arm64-v8a,x86,x86_64
